//
//  IndependenceDay.swift
//  
//
//  Created by Evan Anderson on 6/24/22.
//

import Foundation
import SwiftSovereignStates

enum IndependenceDay : String, CustomHoliday {
    case instance
    
    public func get_date(country: Country, year: Int) -> HolidayDate? {
        switch country {
        case .abkhazia,
                .botswana:
            return HolidayDate(year: year, month: .september, day: 30)
        case .afghanistan: return HolidayDate(year: year, month: .august, day: 19)
        case .albania: return HolidayDate(year: year, month: .november, day: 28)
        case .algeria,
                .venezuela:
            return HolidayDate(year: year, month: .july, day: 5)
        case .angola: return HolidayDate(year: year, month: .november, day: 11)
        case .antigua_and_barbuda: return HolidayDate(year: year, month: .november, day: 1)
        case .argentina,
                .south_sudan:
            return HolidayDate(year: year, month: .july, day: 9)
        case .armenia,
                .belize:
            return HolidayDate(year: year, month: .september, day: 21)
        case .austria: return HolidayDate(year: year, month: .october, day: 26)
        case .azerbaijan: return HolidayDate(year: year, month: .october, day: 18)
        case .bahamas: return HolidayDate(year: year, month: .july, day: 10)
        case .bahrain: return HolidayDate(year: year, month: .december, day: 16)
        case .bangladesh: return HolidayDate(year: year, month: .march, day: 26)
        case .barbados: return HolidayDate(year: year, month: .november, day: 30)
        case .belarus: return HolidayDate(year: year, month: .july, day: 3)
        case .belgium: return HolidayDate(year: year, month: .july, day: 21)
        case .benin: return HolidayDate(year: year, month: .august, day: 1)
        case .bolivia: return HolidayDate(year: year, month: .august, day: 6)
        case .bosnia_and_herzegovina: return HolidayDate(year: year, month: .march, day: 1)
        case .brazil: return HolidayDate(year: year, month: .september, day: 7)
        case .brunei: return HolidayDate(year: year, month: .february, day: 23)
        case .bulgaria: return HolidayDate(year: year, month: .october, day: 5)
        case .burkina_faso: return HolidayDate(year: year, month: .august, day: 5)
        case .burundi: return HolidayDate(year: year, month: .july, day: 1)
        case .cambodia: return HolidayDate(year: year, month: .november, day: 9)
        case .cape_verde: return HolidayDate(year: year, month: .july, day: 5)
        case .central_african_republic: return HolidayDate(year: year, month: .august, day: 13)
        case .chad: return HolidayDate(year: year, month: .august, day: 11)
        case .chile: return HolidayDate(year: year, month: .september, day: 18)
        case .colombia: return HolidayDate(year: year, month: .july, day: 20)
        case .comoros: return HolidayDate(year: year, month: .july, day: 6)
        case .democratic_republic_of_the_congo: return HolidayDate(year: year, month: .june, day: 30)
        case .republic_of_the_congo: return HolidayDate(year: year, month: .august, day: 15)
        case .costa_rica: return HolidayDate(year: year, month: .september, day: 15)
        case .croatia: return HolidayDate(year: year, month: .may, day: 30)
        case .cuba: return HolidayDate(year: year, month: .october, day: 10)
        case .cyprus: return HolidayDate(year: year, month: .october, day: 1)
        case .czech_republic: return HolidayDate(year: year, month: .october, day: 28)
        case .djibouti: return HolidayDate(year: year, month: .june, day: 27)
        case .dominica: return HolidayDate(year: year, month: .november, day: 3)
        case .dominican_republic: return HolidayDate(year: year, month: .february, day: 27)
        case .timor_leste: return HolidayDate(year: year, month: .may, day: 20)
        case .ecuador: return HolidayDate(year: year, month: .august, day: 10)
        case .el_salvador: return HolidayDate(year: year, month: .september, day: 15)
        case .eritrea: return HolidayDate(year: year, month: .may, day: 24)
        case .estonia: return HolidayDate(year: year, month: .february, day: 24)
        case .fiji: return HolidayDate(year: year, month: .october, day: 10)
        case .finland: return HolidayDate(year: year, month: .december, day: 6)
        case .gabon: return HolidayDate(year: year, month: .august, day: 17)
        case .gambia: return HolidayDate(year: year, month: .february, day: 18)
        case .georgia: return HolidayDate(year: year, month: .may, day: 26)
        case .ghana: return HolidayDate(year: year, month: .march, day: 6)
        case .greece: return HolidayDate(year: year, month: .march, day: 25)
        case .guatemala: return HolidayDate(year: year, month: .september, day: 15)
        case .guinea: return HolidayDate(year: year, month: .october, day: 2)
        case .guyana: return HolidayDate(year: year, month: .may, day: 26)
        case .haiti: return HolidayDate(year: year, month: .january, day: 1)
        case .honduras: return HolidayDate(year: year, month: .september, day: 15)
        case .hungary: return HolidayDate.get_last(day_of_week: .saturday, month: .june, year: year)
        case .iceland: return HolidayDate(year: year, month: .june, day: 17)
        case .india: return HolidayDate(year: year, month: .august, day: 15)
        case .indonesia: return HolidayDate(year: year, month: .august, day: 17)
        case .iran: return HolidayDate(year: year, month: .april, day: 1)
        case .iraq: return HolidayDate(year: year, month: .october, day: 3)
        case .ireland: return HolidayDate(year: year, month: .april, day: 24)
        case .ivory_coast: return HolidayDate(year: year, month: .august, day: 7)
        case .jamaica: return HolidayDate(year: year, month: .august, day: 6)
        case .jordan: return HolidayDate(year: year, month: .may, day: 25)
        case .kazakhstan: return HolidayDate(year: year, month: .december, day: 16)
        case .kenya: return HolidayDate(year: year, month: .december, day: 12)
        case .kiribati: return HolidayDate(year: year, month: .july, day: 12)
        case .kuwait: return HolidayDate(year: year, month: .february, day: 25)
        case .kyrgyzstan: return HolidayDate(year: year, month: .december, day: 16)
        case .latvia: return HolidayDate(year: year, month: .may, day: 4)
        case .lebanon: return HolidayDate(year: year, month: .november, day: 22)
        case .liberia: return HolidayDate(year: year, month: .july, day: 26)
        case .libya: return HolidayDate(year: year, month: .december, day: 24)
        case .lithuania: return HolidayDate(year: year, month: .march, day: 11)
        case .madagascar: return HolidayDate(year: year, month: .june, day: 26)
        case .malawi: return HolidayDate(year: year, month: .july, day: 6)
        case .malaysia: return HolidayDate(year: year, month: .august, day: 31)
        case .maldives: return HolidayDate(year: year, month: .july, day: 26)
        case .mali: return HolidayDate(year: year, month: .september, day: 22)
        case .malta: return HolidayDate(year: year, month: .september, day: 21)
        case .mauritania: return HolidayDate(year: year, month: .november, day: 28)
        case .mauritius: return HolidayDate(year: year, month: .march, day: 12)
        case .mexico: return HolidayDate(year: year, month: .september, day: 16)
        case .micronesia: return HolidayDate(year: year, month: .november, day: 3)
        case .moldova: return HolidayDate(year: year, month: .august, day: 27)
        case .mongolia: return HolidayDate(year: year, month: .december, day: 29)
        case .montenegro: return HolidayDate(year: year, month: .may, day: 21)
        case .morocco: return HolidayDate(year: year, month: .november, day: 18)
        case .mozambique: return HolidayDate(year: year, month: .june, day: 25)
        case .myanmar: return HolidayDate(year: year, month: .january, day: 4)
        case .namibia: return HolidayDate(year: year, month: .march, day: 21)
        case .nauru: return HolidayDate(year: year, month: .january, day: 31)
        case .netherlands: return HolidayDate(year: year, month: .june, day: 23)
        case .nicaragua: return HolidayDate(year: year, month: .september, day: 15)
        case .niger: return HolidayDate(year: year, month: .august, day: 3)
        case .nigeria: return HolidayDate(year: year, month: .october, day: 1)
        case .north_korea: return HolidayDate(year: year, month: .august, day: 15)
        case .north_macedonia: return HolidayDate(year: year, month: .september, day: 8)
        case .norway: return HolidayDate(year: year, month: .june, day: 7)
        case .oman: return HolidayDate(year: year, month: .november, day: 18)
        case .pakistan: return HolidayDate(year: year, month: .august, day: 14)
        case .palestine: return HolidayDate(year: year, month: .november, day: 15)
        case .panama: return HolidayDate(year: year, month: .november, day: 3)
        case .papua_new_guinea: return HolidayDate(year: year, month: .september, day: 16)
        case .paraguay: return HolidayDate(year: year, month: .may, day: 15)
        case .peru: return HolidayDate(year: year, month: .july, day: 28)
        case .philippines: return HolidayDate(year: year, month: .june, day: 12)
        case .poland: return HolidayDate(year: year, month: .november, day: 11)
        case .portugal: return HolidayDate(year: year, month: .december, day: 1)
        case .qatar: return HolidayDate(year: year, month: .december, day: 18)
        case .romania: return HolidayDate(year: year, month: .may, day: 9)
        case .rwanda,
                .somalia:
            return HolidayDate(year: year, month: .july, day: 1)
        case .samoa: return HolidayDate(year: year, month: .june, day: 1)
        case .sao_tome_and_principe: return HolidayDate(year: year, month: .july, day: 12)
        case .saudi_arabia: return HolidayDate(year: year, month: .september, day: 23)
        case .senegal: return HolidayDate(year: year, month: .april, day: 4)
        case .serbia: return HolidayDate(year: year, month: .february, day: 15)
        case .seychelles: return HolidayDate(year: year, month: .june, day: 29)
        case .singapore: return HolidayDate(year: year, month: .august, day: 9)
        case .slovakia: return HolidayDate(year: year, month: .july, day: 17)
        case .slovenia: return HolidayDate(year: year, month: .december, day: 26)
        case .solomon_islands: return HolidayDate(year: year, month: .july, day: 7)
        case .south_africa: return HolidayDate(year: year, month: .december, day: 11)
        case .south_korea: return HolidayDate(year: year, month: .march, day: 1)
        case .sri_lanka: return HolidayDate(year: year, month: .february, day: 4)
        case .sudan: return HolidayDate(year: year, month: .january, day: 1)
        case .suriname: return HolidayDate(year: year, month: .november, day: 25)
        case .sweden: return HolidayDate(year: year, month: .june, day: 6)
        case .switzerland: return HolidayDate(year: year, month: .august, day: 1)
        case .syria: return HolidayDate(year: year, month: .april, day: 17)
        case .tajikistan: return HolidayDate(year: year, month: .september, day: 9)
        case .tanzania: return HolidayDate(year: year, month: .december, day: 9)
        case .togo: return HolidayDate(year: year, month: .april, day: 27)
        case .transnistria,
                .vietnam:
            return HolidayDate(year: year, month: .september, day: 2)
        case .trinidad_and_tobago: return HolidayDate(year: year, month: .august, day: 31)
        case .tunisia: return HolidayDate(year: year, month: .march, day: 20)
        case .turkmenistan: return HolidayDate(year: year, month: .september, day: 27)
        case .tuvalu: return HolidayDate(year: year, month: .october, day: 1)
        case .uganda: return HolidayDate(year: year, month: .october, day: 9)
        case .ukraine: return HolidayDate(year: year, month: .august, day: 24)
        case .united_arab_emirates: return HolidayDate(year: year, month: .december, day: 2)
        case .united_states: return HolidayDate(year: year, month: .july, day: 4)
        case .uruguay: return HolidayDate(year: year, month: .august, day: 25)
        case .uzbekistan: return HolidayDate(year: year, month: .september, day: 1)
        case .vanuatu: return HolidayDate(year: year, month: .july, day: 30)
        case .yemen: return HolidayDate(year: year, month: .november, day: 30)
        case .zambia: return HolidayDate(year: year, month: .october, day: 24)
        case .zimbabwe: return HolidayDate(year: year, month: .april, day: 18)
        default:
            return nil
        }
    }
    
    public func get_sources(country: Country) -> HolidaySources {
        let category:HolidaySource = HolidaySource(name: "Wikipedia: Category:Independence_days", url: "https://en.wikipedia.org/wiki/Category:Independence_days")
        let list:HolidaySource = HolidaySource(name: "Wikipedia: List of national independence days", url: "https://en.wikipedia.org/wiki/List_of_national_independence_days")
        return HolidaySources(sources: [category, list])
    }
}
